Parameters:
  DnsFront:
    Description: DNS listening on Apache
    Type: String
    Default: template.example.com
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  AMITemplateApp:
    Description: AMI Template ID of the Application
    Type: String
    Default: 'ami-dd8b3ca0'
    AllowedPattern: '^ami-.*'
    ConstraintDescription: must be a valid AMI ID eg. ami-xxxxxx.
  WebServerCount:
    Description: Number of EC2 instances to launch for the WebServer server
    Type: Number
    Default: '1'
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: ' The IP address range that can be used access the web server using SSH.'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  UserPassword:
    Description: Set password on App instances for user 'ec2-user'.
    Type: String
    MinLength: '8'
    MaxLength: '18'
    Default: 'xxxxxxxxxxx'